Repository AY2324S2-CS2103T-T16-2/tp, pull requests merged in 2024-04, with the labels that each got.

#68 Add days available argument in message usage for EditCommand
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Bug

#70 Implemented lend command
  src/main/java/seedu/address/logic/commands/LendCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/LendCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/LendCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/LendCommandParserTest.java
Labels: type.story

#73 Allow filtering by AND instead of OR
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FilterNameCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/PersonAvailableOnDayPredicate.java
  src/main/java/seedu/address/model/person/predicates/PersonHasTagPredicate.java
  src/test/java/seedu/address/logic/commands/FilterNameCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterTagCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterNameCommandParserTest.java
  src/test/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/PersonAvailableOnDayPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/PersonHasTagPredicateTest.java
Labels: type.Enhancement

#74 Update UG
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/UiBreakdown.png
  docs/images/UiContactClicked.png
Labels: documentation

#76 Add remark command section to User Guide
  docs/UserGuide.md
Labels: documentation

#110 Update Person formatting message
  src/main/java/seedu/address/logic/Messages.java
Labels: type.Bug

#113 Fix messages
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/model/person/Birthday.java
Labels: type.Bug

#118 Update DG for lend and split
  docs/DeveloperGuide.md
  docs/diagrams/LendActivityDiagram.puml
  docs/diagrams/LendClassDiagram.puml
  docs/diagrams/SplitClassDiagram.puml
  docs/images/LendActivityDiagram.png
  docs/images/LendClassDiagram.png
  docs/images/SplitClassDiagram.png
Labels: documentation

#120 Add new upcoming enhancement in ug
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/PayNowWindow.png
  docs/images/SortSequenceDiagram.png
Labels: documentation

#121 Update readme and DG
  README.md
  docs/DeveloperGuide.md
Labels: documentation

#123 Update UG tone
  docs/UserGuide.md
Labels: documentation

#126 Update planned enhancements for DG
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/LendCommand.java
  src/main/java/seedu/address/logic/commands/SplitCommand.java
Labels: documentation

#130 Add future enhancements for name
  docs/DeveloperGuide.md
Labels: documentation

#131 Update planned enhancement
  docs/DeveloperGuide.md
  docs/images/plannedEnhancement2.jpeg
  docs/images/plannedEnhancement3.jpeg
  docs/images/plannedEnhancement4.jpeg
Labels: documentation

#132 Add information on manual testing
  docs/DeveloperGuide.md
  docs/images/RemarkCommandSequenceDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation

#135 Update About Us page
  docs/AboutUs.md
  docs/team/alvinnzz.md
  docs/team/jerryo3.md
  docs/team/newtonkoh.md
  docs/team/zhekaiii.md
Labels: documentation

#133 Comprehensive Update to the FriendFolio User Guide
  docs/DeveloperGuide.md
  docs/Gemfile.lock
  docs/UserGuide.md
  docs/_sass/minima/_layout.scss
  docs/_sass/minima/custom-styles.scss
  docs/assets/css/style.scss
  docs/images/CommandResult.png
  docs/images/Dashboard.png
  docs/images/DisplayCard.png
  docs/images/JarFile.png
  docs/images/Signature.png
  docs/images/UiBreakdown.png
Labels: documentation

#137 Fix help message
  docs/images/helpMessage.png
Labels: documentation
